[tool.poetry]
name = "josepy"
version = "1.12.0.dev0"
description = "JOSE protocol implementation in Python"
license = "Apache License 2.0"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Internet :: WWW/HTTP", 
    "Topic :: Security",
]
homepage = "https://github.com/certbot/josepy"
authors = ["Certbot Project <client-dev@letsencrypt.org>"]
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.6"
# load_pem_private/public_key (>=0.6)
# rsa_recover_prime_factors (>=0.8)
# add sign() and verify() to asymetric keys (RSA >=1.4, ECDSA >=1.5)
cryptography = ">=1.5"
# Connection.set_tlsext_host_name (>=0.13)
pyopenssl = ">=0.13"
# For pkg_resources. >=1.0 so pip resolves it to a version cryptography
# will tolerate; see #2599:
setuptools = ">=1.0"

[tool.poetry.dev-dependencies]
coverage = ">=4.0"
flake8 = "*"
isort = "*"
mypy = "*"
types-pyOpenSSL = "*"
types-pyRFC3339 = "*"
types-requests = "*"
types-setuptools = "*"
pytest = ">=2.8.0"
pytest-cov = "*"
pytest-flake8 = ">=0.5"
tox = "*"
sphinx = {version = ">=1.0", optional = true}  # autodoc_member_order = 'bysource', autodoc_default_flags
sphinx-rtd-theme = {version = ">=1.0", optional = true}

[tool.poetry.extras]
docs = [
    "sphinx",
    "sphinx-rtd-theme",
]

[tool.poetry.scripts]
jws = "josepy.jws:CLI.run"

[tool.mypy]
ignore_missing_imports = true
warn_unused_ignores = true
show_error_codes = true
disallow_untyped_defs = true

[tool.pytest.ini_options]
addopts = "-v --flake8 --cov-report xml --cov-report=term-missing --cov=josepy --cov-config .coveragerc"
filterwarnings = [
    "error",
    # Ignore some deprecation warnings related to interaction between flake8 and pytest.
    "ignore::pytest.PytestDeprecationWarning",
    "ignore:SelectableGroups:DeprecationWarning",
]
norecursedirs = "*.egg .eggs dist build docs .tox"
flake8-ignore = "W504 E501"

[tool.isort]
combine_as_imports = false
default_section = "THIRDPARTY"
include_trailing_comma = true
known_first_party = "josepy"
line_length = 79
multi_line_output = 3

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
